import type {
  AdminCustomerRow,
  AdminCustomerDetailData,
  CustomerStats,
} from "./customer-list-types";
import type { OrderStatus, PaymentStatus } from "@/types/enums";

export const MOCK_ADMIN_CUSTOMERS: AdminCustomerRow[] = [
  {
    id: "cust-001",
    name: "Alex Student",
    email: "alex@example.com",
    phone: "+62 812-9876-5432",
    role: "customer",
    reseller_status: "NOT_RESELLER",
    is_active: true,
    total_orders: 3,
    total_spent: 3450000,
    last_order_at: "2023-10-24T10:15:00Z",
    last_order_status: "DELIVERED" as OrderStatus,
    created_at: "2023-05-10T08:00:00Z",
  },
  {
    id: "cust-002",
    name: "Budi Santoso",
    email: "budi.s@gmail.com",
    phone: "+62 813-2233-4455",
    role: "customer",
    reseller_status: "APPROVED",
    is_active: true,
    total_orders: 8,
    total_spent: 8920000,
    last_order_at: "2023-09-12T14:20:00Z",
    last_order_status: "COMPLETED" as OrderStatus,
    created_at: "2023-02-15T11:30:00Z",
  },
  {
    id: "cust-003",
    name: "Citra Dewi",
    email: "citra.dewi@yahoo.com",
    phone: "+62 819-8765-4321",
    role: "customer",
    reseller_status: "APPROVED",
    is_active: true,
    total_orders: 5,
    total_spent: 6150000,
    last_order_at: "2023-11-02T08:30:00Z",
    last_order_status: "SHIPPED" as OrderStatus,
    created_at: "2023-04-18T09:45:00Z",
  },
  {
    id: "cust-004",
    name: "Dimas Anggara",
    email: "dimas.ang@outlook.com",
    phone: "+62 856-1122-3344",
    role: "customer",
    reseller_status: "NOT_RESELLER",
    is_active: true,
    total_orders: 2,
    total_spent: 980000,
    last_order_at: "2023-11-05T13:45:00Z",
    last_order_status: "PROCESSING" as OrderStatus,
    created_at: "2023-08-01T15:20:00Z",
  },
  {
    id: "cust-005",
    name: "Eka Pratama",
    email: "eka.pratama@gmail.com",
    phone: "+62 878-5566-7788",
    role: "customer",
    reseller_status: "PENDING",
    is_active: true,
    total_orders: 1,
    total_spent: 920000,
    last_order_at: "2023-11-06T16:00:00Z",
    last_order_status: "PENDING" as OrderStatus,
    created_at: "2023-10-15T10:10:00Z",
  },
  {
    id: "cust-006",
    name: "Gina Lestari",
    email: "gina.lestari@sekolah-robot.id",
    phone: "+62 811-9988-7766",
    role: "customer",
    reseller_status: "PENDING",
    is_active: true,
    total_orders: 4,
    total_spent: 4750000,
    last_order_at: "2023-11-01T10:00:00Z",
    last_order_status: "COMPLETED" as OrderStatus,
    created_at: "2023-09-05T14:15:00Z",
  },
  {
    id: "cust-007",
    name: "Fajar Nugraha",
    email: "fajar.n@gmail.com",
    phone: "+62 821-4433-2211",
    role: "customer",
    reseller_status: "REJECTED",
    is_active: true,
    total_orders: 1,
    total_spent: 350000,
    last_order_at: "2023-08-10T09:12:00Z",
    last_order_status: "CANCELLED" as OrderStatus,
    created_at: "2023-07-20T16:30:00Z",
  },
  {
    id: "cust-008",
    name: "Hadi Kusuma",
    email: "hadi.kusuma@gmail.com",
    phone: "+62 817-6655-4433",
    role: "customer",
    reseller_status: "NOT_RESELLER",
    is_active: false,
    total_orders: 0,
    total_spent: 0,
    last_order_at: null,
    last_order_status: null,
    created_at: "2023-01-12T11:00:00Z",
  },
];

export function getCustomerStats(customers: AdminCustomerRow[]): CustomerStats {
  return {
    total_customers: customers.length,
    active_customers: customers.filter((c) => c.is_active).length,
    approved_resellers: customers.filter((c) => c.reseller_status === "APPROVED").length,
    pending_resellers: customers.filter((c) => c.reseller_status === "PENDING").length,
  };
}

export const MOCK_CUSTOMER_DETAILS: Record<string, AdminCustomerDetailData> = {
  "cust-001": {
    id: "cust-001",
    name: "Alex Student",
    email: "alex@example.com",
    phone: "+62 812-9876-5432",
    gender: "MALE",
    tax_id: "92.381.829.1-012.000",
    tax_country: "Indonesia",
    role: "customer",
    reseller_status: "NOT_RESELLER",
    reseller_approved_at: null,
    is_active: true,
    last_login_at: "2023-11-08T09:30:00Z",
    created_at: "2023-05-10T08:00:00Z",
    metrics: {
      total_spent: 3450000,
      total_orders: 3,
      completed_orders: 3,
      cancelled_orders: 0,
      average_order_value: 1150000,
      last_order_at: "2023-10-24T10:15:00Z",
    },
    addresses: [
      {
        id: "addr-001",
        user_id: "cust-001",
        label: "Rumah",
        recipient_name: "Alex Student",
        phone: "+62 812-9876-5432",
        address: "Jl. Margonda Raya No. 120, Beji",
        province: "Jawa Barat",
        city: "Kota Depok",
        district: "Beji",
        village: "Pondok Cina",
        postal_code: "16424",
        is_primary: true,
        created_at: "2023-05-10T08:15:00Z",
        updated_at: "2023-05-10T08:15:00Z",
      },
      {
        id: "addr-002",
        user_id: "cust-001",
        label: "Lab Robotika Kampus",
        recipient_name: "Alex Student (Lab UI)",
        phone: "+62 812-9876-5432",
        address: "Gedung FTUI Lantai 3, Kampus Baru UI",
        province: "Jawa Barat",
        city: "Kota Depok",
        district: "Beji",
        village: "Kukusan",
        postal_code: "16425",
        is_primary: false,
        created_at: "2023-07-14T13:10:00Z",
        updated_at: "2023-07-14T13:10:00Z",
      },
    ],
    orders: [
      {
        id: "ord-001",
        order_number: "ORD-112-9876543-1234567",
        created_at: "2023-10-24T10:15:00Z",
        item_count: 3,
        first_item_name: "Advanced Servo Motor Controller Board V2",
        total: 1850000,
        subtotal: 1800000,
        shipping_cost: 50000,
        discount_amount: 0,
        status: "DELIVERED" as OrderStatus,
        payment_status: "PAID" as PaymentStatus,
        payment_method: "BCA Virtual Account",
        shipping_courier: "J&T Express",
        tracking_number: "JNT98765431234",
      },
      {
        id: "ord-001-prev1",
        order_number: "ORD-20230715-0012",
        created_at: "2023-07-15T14:30:00Z",
        item_count: 2,
        first_item_name: "RoboKit Smart Obstacle Avoidance Car",
        total: 1150000,
        subtotal: 1125000,
        shipping_cost: 25000,
        discount_amount: 0,
        status: "COMPLETED" as OrderStatus,
        payment_status: "PAID" as PaymentStatus,
        payment_method: "GoPay",
        shipping_courier: "J&T Express",
        tracking_number: "JNT7765123490",
      },
      {
        id: "ord-001-prev2",
        order_number: "ORD-20230520-0004",
        created_at: "2023-05-20T11:00:00Z",
        item_count: 1,
        first_item_name: "Ultrasonic Distance Sensor HC-SR04 (Pack of 5)",
        total: 450000,
        subtotal: 430000,
        shipping_cost: 20000,
        discount_amount: 0,
        status: "COMPLETED" as OrderStatus,
        payment_status: "PAID" as PaymentStatus,
        payment_method: "QRIS",
        shipping_courier: "J&T Express",
        tracking_number: "JNT5544332211",
      },
    ],
    complaints: [
      {
        id: "cmp-001",
        order_id: "ord-001",
        order_number: "ORD-112-9876543-1234567",
        title: "Konektor pin servo longgar pada board",
        description: "Saat unboxing salah satu pin header pada channel 3 sedikit bengkok.",
        status: "RESOLVED",
        created_at: "2023-10-26T14:00:00Z",
      },
    ],
    reviews: [
      {
        id: "rev-001",
        product_name: "Advanced Servo Motor Controller Board V2",
        rating: 5,
        comment: "Kualitas board sangat presisi dan bekerja sempurna dengan Arduino Uno. Sangat direkomendasikan!",
        status: "PUBLISHED",
        created_at: "2023-10-30T16:20:00Z",
      },
      {
        id: "rev-002",
        product_name: "RoboKit Smart Obstacle Avoidance Car",
        rating: 5,
        comment: "Sangat edukatif untuk praktikum siswa robotika!",
        status: "PUBLISHED",
        created_at: "2023-07-22T10:00:00Z",
      },
    ],
  },
};

/**
 * Helper untuk mengambil data mock customer by ID.
 * Bila ID tidak ada di dictionary khusus, buat fallback detail dinamis dari MOCK_ADMIN_CUSTOMERS.
 */
export function getMockCustomerDetail(id: string): AdminCustomerDetailData | null {
  if (MOCK_CUSTOMER_DETAILS[id]) {
    return MOCK_CUSTOMER_DETAILS[id];
  }

  const basic = MOCK_ADMIN_CUSTOMERS.find((c) => c.id === id);
  if (!basic) return null;

  return {
    id: basic.id,
    name: basic.name,
    email: basic.email,
    phone: basic.phone,
    gender: null,
    tax_id: null,
    tax_country: null,
    role: basic.role,
    reseller_status: basic.reseller_status,
    reseller_approved_at: basic.reseller_status === "APPROVED" ? "2023-03-01T10:00:00Z" : null,
    is_active: basic.is_active,
    last_login_at: basic.created_at,
    created_at: basic.created_at,
    metrics: {
      total_spent: basic.total_spent,
      total_orders: basic.total_orders,
      completed_orders: basic.total_orders,
      cancelled_orders: 0,
      average_order_value: basic.total_orders > 0 ? Math.round(basic.total_spent / basic.total_orders) : 0,
      last_order_at: basic.last_order_at,
    },
    addresses: [
      {
        id: `addr-${basic.id}-1`,
        user_id: basic.id,
        label: "Alamat Pengiriman Utama",
        recipient_name: basic.name,
        phone: basic.phone || "+62 812-0000-0000",
        address: "Jl. Pendidikan Robotika No. 88",
        province: "DKI Jakarta",
        city: "Jakarta Selatan",
        district: "Kebayoran Baru",
        village: "Melawai",
        postal_code: "12160",
        is_primary: true,
        created_at: basic.created_at,
        updated_at: basic.created_at,
      },
    ],
    orders: basic.last_order_at
      ? [
          {
            id: `ord-${basic.id}-1`,
            order_number: `ORD-${basic.id.toUpperCase()}-001`,
            created_at: basic.last_order_at,
            item_count: 2,
            first_item_name: "RoboEdu Kit Smart Starter Edition",
            total: basic.total_spent,
            subtotal: basic.total_spent - 30000,
            shipping_cost: 30000,
            discount_amount: 0,
            status: (basic.last_order_status as OrderStatus) || "COMPLETED",
            payment_status: "PAID" as PaymentStatus,
            payment_method: "BCA Virtual Account",
            shipping_courier: "J&T Express",
            tracking_number: "JNT1234567890",
          },
        ]
      : [],
    complaints: [],
    reviews: [],
  };
}
